export * from './Blog'
export * from './BlogDetail'
export * from './Newsletter'
export * from './Projects'
export * from './About'
export * from './posts'
export * from './Login'
export * from './Register'